import type { ClientConfig } from './types';

export const CLIENTS: ClientConfig[] = [
  {
    client_id: 'bk_bf',
    nom: 'Burger King France / Bertrand Franchise',
    nom_court: 'BK/BF',
    secteurs: ['restauration rapide', 'franchise', 'hôtellerie restauration'],
    sujet_instit:
      'Régulation de la franchise et restauration rapide, droit du travail HCR, fiscalité alimentation et budget PLF, emballages plastique et consigne',
    acteurs_suivis: [
      'Olivier Bertrand',
      'Guillaume Pépy',
      'Marc Veyrat',
      'Olivia Grégoire',
      'Agnès Pannier-Runacher',
      'Christine Lavarde',
      'Claude Raynal',
      'Jean-François Husson',
      'Stéphane Sautarel',
      'Thierry Cozic',
    ],
    mots_cles: [
      'franchise',
      'restauration',
      'fast food',
      'burger',
      'HCR',
      'emballages',
      'plastique',
      'consigne',
      'SMIC',
      'temps partiel',
      'travail dominical',
      'Nutri-Score',
      'taxe soda',
      'TVA restauration',
      'apprentissage restauration',
      'PLF',
      'budget',
      'commission des finances',
      'rapporteur général',
      'planification écologique',
      'bœuf',
      'viande bovine',
      'Mercosur',
      'volaille',
    ],
    slack_channel_id: 'C0AGMK2EFKK', // #bertrand-franchise
    notion_hub_id: '33c5afd3-7b97-810e-ab45-e7113723892a',
  },
  {
    client_id: 'france_travail',
    nom: 'France Travail',
    nom_court: 'France Travail',
    secteurs: ["service public de l'emploi", 'opérateur public', 'insertion professionnelle'],
    sujet_instit:
      "Service public de l'emploi, réforme assurance chômage, formation professionnelle — protection budget PLF/ETP",
    acteurs_suivis: [
      'Astrid Panosyan-Bouvet',
      'Thibaut Guilluy',
      'Marc Ferracci',
      'Jean-Luc Vergne',
      'Patricia Ferrand',
      'Juvin',
      'Pujol',
      'Thibaut Duchene',
      'Stéphanie Rist',
      'Christine Lavarde',
    ],
    mots_cles: [
      'France Travail',
      'chômage',
      'assurance chômage',
      'formation professionnelle',
      'CPF',
      'apprentissage',
      'insertion',
      'RSA',
      'contrat engagement jeune',
      "demandeur d'emploi",
      'Pôle emploi',
      'AFPA',
      'missions locales',
      'plein emploi',
      'loi plein emploi',
      'frontaliers',
      'agencification',
      'ETP',
      'PLF 2027',
    ],
    slack_channel_id: 'C0AQDJ549CK', // #france-travail
    notion_hub_id: '33c5afd3-7b97-8149-8aa3-fcfbaf5f4642',
  },
  {
    client_id: 'lidl',
    nom: 'LIDL France',
    nom_court: 'LIDL',
    secteurs: ['grande distribution', 'commerce alimentaire', 'hard discount'],
    sujet_instit:
      'Relations commerciales grande distribution, Egalim, prix alimentaires, concurrence distribution',
    acteurs_suivis: [
      'Benoît Soury',
      'Olivia Grégoire',
      'Agnès Pannier-Runacher',
      'Thierry Cotillard',
      'Dominique Schelcher',
    ],
    mots_cles: [
      'grande distribution',
      'hard discount',
      'Egalim',
      'SRP',
      'relations commerciales',
      'négociation commerciale',
      'prix alimentation',
      'DGCCRF',
      'concurrence',
      'marges',
      'fournisseurs',
      'emballages',
      'LIDL',
      'inflation alimentaire',
      'commission enquête',
      'Descrozaille',
    ],
    slack_channel_id: 'C0AQPHFKFA8', // #lidl
    notion_hub_id: '33c5afd3-7b97-819c-b188-ff11dd1721db',
  },
  {
    client_id: 'sodiaal',
    nom: 'Sodiaal',
    nom_court: 'Sodiaal',
    secteurs: ['coopérative laitière', 'agriculture', 'agroalimentaire', 'filière lait'],
    sujet_instit:
      'Filière laitière française, politique agricole, prix du lait, transition écologique élevage',
    acteurs_suivis: [
      'Marc Pagès',
      'Annie Genevard',
      'Julien Denormandie',
      'Laurent Duplomb',
      'Fabrice Pannekoucke',
    ],
    mots_cles: [
      'lait',
      'laitier',
      'coopérative',
      'CNIEL',
      'élevage',
      'PAC',
      "bien-être animal",
      'méthane bovin',
      'filière bovine',
      'décarbonation',
      'agriculture durable',
      'fromage',
      'Sodiaal',
      'FNPL',
      'urgence agricole',
    ],
    slack_channel_id: 'C0AQGHGNEJH', // #sodiaal
    notion_hub_id: '33c5afd3-7b97-818c-a7cb-c300011522b6',
  },
  {
    client_id: 'wecasa',
    nom: 'Wecasa',
    nom_court: 'Wecasa',
    secteurs: ['services à domicile', 'plateforme numérique', 'travail indépendant', 'SAP'],
    sujet_instit:
      'Régulation des plateformes de services, statut travailleur indépendant, services à la personne',
    acteurs_suivis: [
      'Astrid Panosyan-Bouvet',
      'Marc Ferracci',
      'Amélie de Montchalin',
      'Thomas Cazenave',
    ],
    mots_cles: [
      'services à la personne',
      'SAP',
      'plateforme',
      'auto-entrepreneur',
      'indépendant',
      'CESU',
      'aide domicile',
      'statut plateforme',
      'présomption salariat',
      'ubérisation',
      "crédit d'impôt domicile",
      'Nova certification',
      'Wecasa',
      'DSA',
      'directive plateformes',
    ],
    slack_channel_id: 'C0AQDJA5H0T', // #wecasa
    notion_hub_id: '33c5afd3-7b97-81ef-b3c8-df93df2b6b6a',
  },
  {
    client_id: 'cnajmj',
    nom: 'CNAJMJ',
    nom_court: 'CNAJMJ',
    secteurs: [
      'professions réglementées',
      'justice',
      'procédures collectives',
      'mandataires judiciaires',
    ],
    sujet_instit:
      'Droit des entreprises en difficulté, professions réglementées du chiffre et du droit, réforme judiciaire',
    acteurs_suivis: [
      'Gérald Darmanin',
      'Michel Barnier',
      'Hélène Bourbouloux',
      'Christiane Feral-Schuhl',
      'François Molins',
      'Didier Kling',
      'Sébastien Velez',
    ],
    mots_cles: [
      'administrateur judiciaire',
      'mandataire judiciaire',
      'procédures collectives',
      'liquidation',
      'redressement',
      'sauvegarde',
      'tribunal commerce',
      'CNAJMJ',
      "entreprises en difficulté",
      'restructuration',
      'insolvabilité',
      'professions réglementées',
      'réforme judiciaire',
      'TAE',
      'directive insolvabilité',
    ],
    slack_channel_id: 'C0AL8PWFYPR', // #cnajmj
    notion_hub_id: '33c5afd3-7b97-8115-8c3d-c2b97d395ecb',
  },
];
