import type { ClientConfig } from './types';

export const CLIENTS: ClientConfig[] = [
  {
    client_id: 'bk_bf',
    nom: 'Burger King France / Bertrand Franchise',
    nom_court: 'BK/BF',
    secteurs: ['restauration rapide', 'franchise', 'hôtellerie restauration'],
    sujet_instit:
      'Régulation de la franchise et restauration rapide, droit du travail HCR, fiscalité alimentation et budget PLF, emballages plastique et consigne',
    acteurs_suivis: [
      'Olivier Bertrand',
      'Guillaume Pépy',
      'Marc Veyrat',
      'Olivia Grégoire',
      'Agnès Pannier-Runacher',
      'Stéphane Travert',
      'Julien Dive',
      'Catherine Dumas',
      'Boris Tavernier',
      'Cyrille Isaac-Sibille',
      'Annie Genevard',
      'Serge Papin',
      'Stéphane Viry',
      'Christophe Blanchet',
      'Sophie Prima',
      // PLF / Sénat finances
      'Christine Lavarde',
      'Claude Raynal',
      'Jean-François Husson',
      'Stéphane Sautarel',
      'Thierry Cozic',
    ],
    mots_cles: [
      'franchise',
      'restauration',
      'fast food',
      'burger',
      'HCR',
      'emballages',
      'plastique',
      'consigne',
      'SMIC',
      'temps partiel',
      'travail dominical',
      'Nutri-Score',
      'taxe soda',
      'TVA restauration',
      'apprentissage restauration',
      'taxe fast-food',
      'CDAC',
      'PFAS',
      'Origine France',
      'restauration commerciale',
      'franchise et taxe franchise',
      // PLF / budget
      'PLF',
      'budget',
      'commission des finances',
      'rapporteur général',
      'planification écologique',
      // Agriculture / approvisionnement
      'bœuf',
      'viande bovine',
      'Mercosur',
      'volaille',
    ],
    slack_channel_id: 'C0AGMK2EFKK', // #bertrand-franchise
    notion_hub_id: '33c5afd3-7b97-810e-ab45-e7113723892a',
  },
  {
    client_id: 'france_travail',
    nom: 'France Travail',
    nom_court: 'France Travail',
    secteurs: ["service public de l'emploi", 'opérateur public', 'insertion professionnelle'],
    sujet_instit:
      "Service public de l'emploi, réforme assurance chômage, formation professionnelle — protection budget PLF/ETP",
    acteurs_suivis: [
      'Astrid Panosyan-Bouvet',
      'Thibaut Guilluy',
      'Marc Ferracci',
      'Jean-Luc Vergne',
      'Patricia Ferrand',
      'Stéphanie Rist',
      'Thibaut Bazin',
      'Frédérique Puissat',
      'Christine Lavarde',
      'Mathieu Darnaud',
      // Cibles PLF / budget
      'Juvin',
      'Pujol',
      'Thibaut Duchene',
    ],
    mots_cles: [
      'France Travail',
      'chômage',
      'assurance chômage',
      'formation professionnelle',
      'CPF',
      'apprentissage',
      'RSA',
      'contrat engagement jeune',
      "demandeur d'emploi",
      'Pôle emploi',
      'AFPA',
      'missions locales',
      'Cap emploi',
      'accompagnement',
      'plein emploi',
      'loi plein emploi',
      'insertion',
      'assurance chômage des frontaliers',
      'frontaliers',
      'emploi des seniors',
      'emploi des femmes',
      'rupture conventionnelle',
      'agencification',
      "agences de l'État",
      'ETP',
      'PLF 2027',
    ],
    slack_channel_id: 'C0AQDJ549CK', // #france-travail
    notion_hub_id: '33c5afd3-7b97-8149-8aa3-fcfbaf5f4642',
  },
  {
    client_id: 'lidl',
    nom: 'LIDL France',
    nom_court: 'LIDL',
    secteurs: ['grande distribution', 'commerce alimentaire', 'hard discount'],
    sujet_instit:
      'Relations commerciales grande distribution, Egalim, prix alimentaires, concurrence distribution, RSE et droit du travail',
    acteurs_suivis: [
      'Benoît Soury',
      'Olivia Grégoire',
      'Agnès Pannier-Runacher',
      'Thierry Cotillard',
      'Dominique Schelcher',
      'Laurent Duplomb',
      'Fabrice Pannekoucke',
      'Stéphane Travert',
      'Julien Dive',
      'Franck Menonville',
      'Pierre Cuypers',
      'Serge Papin',
      'Mathieu Lefèvre',
      'Jean-Michel Javelle',
      'Antoine Colette',
      'Anne-Catherine Loisier',
      'Antoine Guhl',
      'Richard Ramos',
      'Nicole Le Peih',
      'Pascal Lecamp',
      'Marie Pochon',
      'Aurélie Trouvé',
      'Marc Fesneau',
      'Vincent Louault',
      'Jean-Claude Tissot',
      'Marie-Lise Housseau',
      'Serge Mérillou',
      'Dominique Estrosi-Sassone',
      'Yves Bleunven',
      'Mathieu Landon',
      'Bruno Bonnel',
      'Thomas Courbe',
    ],
    mots_cles: [
      'grande distribution',
      'hard discount',
      'LIDL',
      'Egalim',
      'SRP',
      'SRP+10',
      'relations commerciales',
      'négociation commerciale',
      'négociations commerciales',
      'contractualisation',
      'déférencement',
      'tunnels de prix',
      'centrales d\'achat',
      'prix alimentation',
      'DGCCRF',
      'concurrence',
      'marges',
      'fournisseurs',
      'MDD',
      'ILEC',
      'FCD',
      'médiation des relations commerciales',
      'emballages',
      'inflation alimentaire',
      'commission enquête',
      'Descrozaille',
      'Nutri-Score',
      'Nutriscore',
      'alimentation ultra-transformée',
      'PNNS',
      'SNANC',
      'restauration collective',
      'Mercosur',
      'droits de douane',
      'souveraineté alimentaire',
      'shrinkflation',
    ],
    slack_channel_id: 'C0AQPHFKFA8', // #lidl
    notion_hub_id: '33c5afd3-7b97-819c-b188-ff11dd1721db',
  },
  {
    client_id: 'sodiaal',
    nom: 'Sodiaal',
    nom_court: 'Sodiaal',
    secteurs: ['coopérative laitière', 'agriculture', 'agroalimentaire', 'filière lait'],
    sujet_instit:
      'Filière laitière française, politique agricole, prix du lait, transition écologique élevage, Egalim et relations commerciales GD',
    acteurs_suivis: [
      'Marc Pagès',
      'Annie Genevard',
      'Julien Denormandie',
      'Laurent Duplomb',
      'Fabrice Pannekoucke',
      'Stéphane Travert',
      'Julien Dive',
      'Franck Menonville',
      'Pierre Cuypers',
      'Serge Papin',
      'Mathieu Lefèvre',
      'Jean-Michel Javelle',
      'Antoine Colette',
      'Anne-Catherine Loisier',
      'Antoine Guhl',
      'Richard Ramos',
      'Nicole Le Peih',
      'Pascal Lecamp',
      'Marie Pochon',
      'Aurélie Trouvé',
      'Marc Fesneau',
      'Vincent Louault',
      'Jean-Claude Tissot',
      'Marie-Lise Housseau',
      'Serge Mérillou',
      'Dominique Estrosi-Sassone',
      'Yves Bleunven',
      'Mathieu Landon',
      'Bruno Bonnel',
      'Thomas Courbe',
    ],
    mots_cles: [
      'lait',
      'laitier',
      'coopérative',
      'coopérative laitière',
      'CNIEL',
      'FNPL',
      'Sodiaal',
      'Candia',
      'Yoplait',
      'Entremont',
      'prix du lait',
      'élevage',
      'PAC',
      'bien-être animal',
      'méthane bovin',
      'filière bovine',
      'décarbonation',
      'agriculture durable',
      'fromage',
      'urgence agricole',
      'Egalim',
      'SRP',
      'contractualisation',
      'négociations commerciales',
      'grande distribution',
      'souveraineté laitière',
      'renouvellement des générations',
      'installation agricole',
      'foncier agricole',
      'Nutri-Score',
      'alimentation ultra-transformée',
      'PNNS',
      'SNANC',
      'restauration collective',
      'poudre de lait',
      'laits infantiles',
      'Mercosur',
      'droits de douane',
      'AOP',
      'produits de montagne',
      'exportations laitières',
    ],
    slack_channel_id: 'C0AQGHGNEJH', // #sodiaal
    notion_hub_id: '33c5afd3-7b97-818c-a7cb-c300011522b6',
  },
  {
    client_id: 'wecasa',
    nom: 'Wecasa',
    nom_court: 'Wecasa',
    secteurs: ['services à domicile', 'plateforme numérique', 'travail indépendant', 'SAP'],
    sujet_instit:
      'Régulation des plateformes de services, transposition directive UE plateformes, crédit d\'impôt SAP, statut travailleur indépendant',
    acteurs_suivis: [
      'Astrid Panosyan-Bouvet',
      'Marc Ferracci',
      'Amélie de Montchalin',
      'Roland Lescure',
      'Philippe Juvin',
      'Daniel Labaronne',
      'Danielle Simonet',
      'Pascal Savoldelli',
      'Serge Papin',
    ],
    mots_cles: [
      'services à la personne',
      'SAP',
      'plateforme',
      'auto-entrepreneur',
      'indépendant',
      'CESU',
      'aide domicile',
      'aides à la personne',
      'présomption salariat',
      'ubérisation',
      "crédit d'impôt domicile",
      "crédit impôt service à domicile",
      'travailleurs non déclarés',
      'URSSAF',
      'plateformes numériques',
      'statut plateforme',
      'directive plateformes',
      'directive travailleurs des plateformes',
      'DSA',
      'Nova certification',
      'Wecasa',
    ],
    slack_channel_id: 'C0AQDJA5H0T', // #wecasa
    notion_hub_id: '33c5afd3-7b97-81ef-b3c8-df93df2b6b6a',
  },
  {
    client_id: 'cnajmj',
    nom: 'CNAJMJ',
    nom_court: 'CNAJMJ',
    secteurs: [
      'professions réglementées',
      'justice',
      'procédures collectives',
      'mandataires judiciaires',
    ],
    sujet_instit:
      'Droit des entreprises en difficulté, professions réglementées du droit, réforme judiciaire, tarifs réglementés et directive insolvabilité UE',
    acteurs_suivis: [
      'Gérald Darmanin',
      'Michel Barnier',
      'Hélène Bourbouloux',
      'Christiane Feral-Schuhl',
      'François Molins',
      'Didier Kling',
      'Aurélie Trouvé',
      'Serge Papin',
      'Roland Lescure',
      'Thomas Courbe',
      'Olivier Rietmann',
    ],
    mots_cles: [
      'administrateur judiciaire',
      'mandataire judiciaire',
      'procédures collectives',
      'liquidation',
      'redressement',
      'sauvegarde',
      'tribunal commerce',
      'tribunal de commerce',
      'CNAJMJ',
      "entreprises en difficulté",
      'défaillances d\'entreprises',
      'restructuration',
      'insolvabilité',
      'professions réglementées',
      'professions judiciaires',
      'réforme judiciaire',
      'Livre VI',
      'TAE',
      'directive insolvabilité',
      'AGS',
      'TRACFIN',
      'financement des entreprises',
      'fonds spéculatifs',
      'prédation capacités productives',
      'tarifs réglementés',
    ],
    slack_channel_id: 'C0AL8PWFYPR', // #cnajmj
    notion_hub_id: '33c5afd3-7b97-8115-8c3d-c2b97d395ecb',
  },
];
